### ISSUE TITLE
API- /deleteitem/:itemID

### ISSUE THREAD

**Issue by Blyndone** [Blyndone/BudgetBites#8]
Create an API call to delete an item from the database

**Comment by AnvarSul** [comment]
i call this one

**Comment by AnvarSul** [comment]
try {
    const itemID = req.params.itemid;
    console.log('Attempting to delete item with ID:', itemID);

    // delete or update reservations referencing the item
    await connection.promise().query('DELETE FROM reserved WHERE itemID = ?', [itemID]);

    // delete or update listings referencing the item
    await connection.promise().query('DELETE FROM listing WHERE itemID = ?', [itemID]);

    // delete the item
    await connection.promise().query('DELETE FROM items WHERE itemID = ?', [itemID]);

    res.status(200).json({ message: 'Item and records deleted successfully' });
  } catch (err) {
    console.error('Error:', err);
    res.status(500).json({ message: 'Internal Server Error', error: err.message });
  }
});
