### ISSUE TITLE
API- /deletereservation/:reservationid

### ISSUE THREAD

**Issue by Blyndone** [Blyndone/BudgetBites#9]
Create an API call to delete a reservation

**Comment by AnvarSul** [comment]
this one too, anvar

**Comment by AnvarSul** [comment]
try {
    const reservationID = req.params.reservationid; 

    console.log('Attempting to delete reservation with ID:', reservationID);

    // Check if the reservation exists
    const [findResult] = await connection.promise().query('SELECT * FROM reserved WHERE reservationID = ?', [reservationID]);
    if (findResult.length === 0) {
      return res.status(404).json({ message: 'Reservation not found' });
    }

    // Delete the reservation
    await connection.promise().query('DELETE FROM reserved WHERE reservationID = ?', [reservationID]);
    res.status(200).json({ message: 'Reservation deleted successfully' });
  } catch (error) {
    console.error(error); // Logging the error
    res.status(500).json({ message: 'Internal Server Error', error: error.message });
  }
});

**Comment by Blyndone** [comment]
Good Job.
